steps:
  - name: node:16
    entrypoint: yarn
    args: ['install']
  - name: node:16
    entrypoint: yarn
    args: ['build']
    env:
      - 'NEXT_PUBLIC_ALGOLIA_APPLICATION_ID=${_NEXT_PUBLIC_ALGOLIA_APPLICATION_ID}'
      - 'NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=${_NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY}'
      - 'ALGOLIA_ADMIN_API_KEY=${_ALGOLIA_ADMIN_API_KEY}'
      - 'SENDGRID_API_KEY=${_SENDGRID_API_KEY}'
      - 'SENDGRID_FROM_EMAIL_ADDRESS=${_SENDGRID_FROM_EMAIL_ADDRESS}'
      - 'SENDGRID_TEMPLATE_ID=${_SENDGRID_TEMPLATE_ID}'
      - 'NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN=${_NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN}'
      - 'NEXT_PUBLIC_MICROCMS_API_KEY=${_NEXT_PUBLIC_MICROCMS_API_KEY}'
      - 'SLACK_WEBHOOK_URL=${_SLACK_WEBHOOK_URL}'
  - name: 'bash'
    args: ['printenv']
  - name: gcr.io/cloud-builders/gcloud
    args:
      ['app', 'deploy', '$BRANCH_NAME.yml', '--project=scrumy-hp', '--quiet']
