steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        cat << EOF > secret.yml
        env_variables:
          SENDGRID_API_KEY: ${_SENDGRID_API_KEY}
          SENDGRID_FROM_EMAIL_ADDRESS: ${_SENDGRID_FROM_EMAIL_ADDRESS}
          SENDGRID_TEMPLATE_ID: ${_SENDGRID_TEMPLATE_ID}
          SLACK_WEBHOOK_URL_HP: ${_SLACK_WEBHOOK_URL_HP}
          SLACK_WEBHOOK_URL_BLOG: ${_SLACK_WEBHOOK_URL_BLOG}
        EOF
  - name: node:16
    entrypoint: yarn
    args: ['install']
  - name: node:16
    entrypoint: yarn
    args: ['build']
    env:
      - 'NEXT_PUBLIC_ALGOLIA_APPLICATION_ID=${_NEXT_PUBLIC_ALGOLIA_APPLICATION_ID}'
      - 'NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=${_NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY}'
      - 'ALGOLIA_ADMIN_API_KEY=${_ALGOLIA_ADMIN_API_KEY}'
      - 'NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN=${_NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN}'
      - 'NEXT_PUBLIC_MICROCMS_API_KEY=${_NEXT_PUBLIC_MICROCMS_API_KEY}'
      - 'NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN2=${_NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN2}'
      - 'NEXT_PUBLIC_MICROCMS_API_KEY2=${_NEXT_PUBLIC_MICROCMS_API_KEY2}'
      - 'NEXT_PUBLIC_GOOGLE_ANALYTICS_ID_PRIMARY=${_NEXT_PUBLIC_GOOGLE_ANALYTICS_ID_PRIMARY}'
      - 'NEXT_PUBLIC_GOOGLE_ANALYTICS_ID_SECONDARY=${_NEXT_PUBLIC_GOOGLE_ANALYTICS_ID_SECONDARY}'
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        'app',
        'deploy',
        'app.$BRANCH_NAME.yml',
        '--project=scrumy-hp',
        '--quiet',
      ]
